### ISSUE TITLE
docker image failed 

### ISSUE THREAD

**Issue by robertzeibich** [GCS-ZHN/SoCube#5]
Tried the docker image:

```
singularity exec socube_latest.sif socube -i /scratch/xm41/RNA-seq-public/snRNA_robert/raw_data/adata_cb_qc_20241226/HSB237.h5ad -o /scratch/xm41/RNA-seq-public/snRNA_robert/raw_data/adata_cb_qc_20241226/HSB237_socube.h5ad
INFO:    underlay of /etc/localtime required more than 50 (68) bind mounts
2024-12-28 18:39:17,108 - numexpr.utils - INFO - Note: NumExpr detected 52 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2024-12-28 18:39:17,108 - numexpr.utils - INFO - NumExpr defaulting to 8 threads.
2024-12-28 18:39:18,624 - Config - INFO - Load required modules
Traceback (most recent call last):
  File "/opt/conda/bin/socube", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/socube/__init__.py", line 173, in main
    import scanpy as sc
  File "/opt/conda/lib/python3.8/site-packages/scanpy/__init__.py", line 14, in <module>
    from . import tools as tl
  File "/opt/conda/lib/python3.8/site-packages/scanpy/tools/__init__.py", line 1, in <module>
    from ..preprocessing import pca
  File "/opt/conda/lib/python3.8/site-packages/scanpy/preprocessing/__init__.py", line 1, in <module>
    from ._recipes import recipe_zheng17, recipe_weinreb17, recipe_seurat
  File "/opt/conda/lib/python3.8/site-packages/scanpy/preprocessing/_recipes.py", line 8, in <module>
    from ._deprecated.highly_variable_genes import (
  File "/opt/conda/lib/python3.8/site-packages/scanpy/preprocessing/_deprecated/highly_variable_genes.py", line 11, in <module>
    from .._utils import _get_mean_var
  File "/opt/conda/lib/python3.8/site-packages/scanpy/preprocessing/_utils.py", line 46, in <module>
    def sparse_mean_var_minor_axis(data, indices, major_len, minor_len, dtype):
  File "/opt/conda/lib/python3.8/site-packages/numba/core/decorators.py", line 212, in wrapper
    disp.enable_caching()
  File "/opt/conda/lib/python3.8/site-packages/numba/core/dispatcher.py", line 863, in enable_caching
    self._cache = FunctionCache(self.py_func)
  File "/opt/conda/lib/python3.8/site-packages/numba/core/caching.py", line 601, in __init__
    self._impl = self._impl_class(py_func)
  File "/opt/conda/lib/python3.8/site-packages/numba/core/caching.py", line 337, in __init__
    raise RuntimeError("cannot cache function %r: no locator available "
RuntimeError: cannot cache function 'sparse_mean_var_minor_axis': no locator available for file '/opt/conda/lib/python3.8/site-packages/scanpy/preprocessing/_utils.py'
```

**Comment by GCS-ZHN** [comment]
We did not test and provide the apptainer (formerly singularity) image. The SIF image file you tested may have been built from scratch or converted from a dockerhub image, but I'm not sure it works. Judging from the logs, you may need to reinstall scanpy as a dependency, I recommend using apptainer's sandbox mode to debug it.

**Comment by robertzeibich** [comment]
Thx for the reply. I got the tool in a conda env running. 
The tool runs for an hour with GPU enabled, which is pretty long.
